// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlgnn4MAZBj3vzT2jP3llxYlO42Yzl5Qw',
    appId: '1:599167370092:web:640d768f6bb00d9474a949',
    messagingSenderId: '599167370092',
    projectId: 'scholar-chat-370c7',
    authDomain: 'scholar-chat-370c7.firebaseapp.com',
    storageBucket: 'scholar-chat-370c7.appspot.com',
    measurementId: 'G-CRNSCTVS29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgc_zuBytXV8H0hukGmOKPKanKKQKbig0',
    appId: '1:599167370092:android:6195cc5e721aec9f74a949',
    messagingSenderId: '599167370092',
    projectId: 'scholar-chat-370c7',
    storageBucket: 'scholar-chat-370c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz4Qwb8RwkxLrFB2hdcIcCQrgWFlIyi9Y',
    appId: '1:599167370092:ios:f375bf7ea67fb5ac74a949',
    messagingSenderId: '599167370092',
    projectId: 'scholar-chat-370c7',
    storageBucket: 'scholar-chat-370c7.appspot.com',
    iosBundleId: 'com.example.scholarChat',
  );
}
